server:
  port: 9100
  address: 0.0.0.0
spring:
  datasource:
    username: sa
    password: 123qwe!@#
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=ASK_CFYL_DB
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: html
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
pagehelper:
  helperDialect: sqlserver